### ISSUE TITLE
datecmp 기반 기술 조사

### ISSUE THREAD

**Issue by DrNeuroAI** [DrNeuroAI/Assignment2#22]
날짜(월/일)을 비교하기 위해서는 tm 구조체의 멤버 변수 중 현재 몇 월/일 인지에 해당하는 int형 tm_mon과 tm_mday를 사용합니다.
tm_mon 변수 값의 범위는 0~11인데, 월은 1~12월이므로 월을 출력하고자 한다면 tm_mon+1을 출력해야 합니다.
tm_mday 변수 값의 범위는 1~31이고, 월과 다르게 일을 출력하고자 한다면 그대로 tm_mday를 출력하면 됩니다.

**Comment by byoung-min** [comment]
2021-05-06 Byoung-min 확인

**Comment by jangsik2** [comment]
2021-05-06 확인
