### ISSUE TITLE
timecmp 관련 기술 조사

### ISSUE THREAD

**Issue by DrNeuroAI** [DrNeuroAI/Assignment2#25]
수정 시간(시/분) 비교를 하기 위해 tm 구조체의 멤버 변수 중 현재 몇 시/분 인지에 해당하는 int형 tm_hour, tm_min를 사용합니다.
tm_hour 변수 값의 범위는 0~23이고 tm_min 변수 값의 범위는 0~59입니다.

**Comment by byoung-min** [comment]
2021-05-06 Byoung-min 확인

**Comment by jangsik2** [comment]
2021-05-06 확인
