### ISSUE TITLE
filestat 기반 기술 조사

### ISSUE THREAD

**Issue by jangsik2** [DrNeuroAI/Assignment2#28]
filestat 함수에서는 파일의 정보를 받아오는 함수이기 때문에 stat() 함수를 사용합니다. stat()함수의 인자로는 const char* path, struct stat* buf를 받는데 이때 path는 파일의 경로, buf는 파일의 정보가 들어갈 구조체 포인터입니다. 따라서 구현할 때 path에는 text1, text2를 입력하고 buf에는 구조체 변수 stat1, stat2를 입력하면 될 것 같습니다.

**Comment by jangsik2** [comment]
filestat 함수에서는 파일의 정보를 받아오는 함수이기 때문에 stat() 함수를 사용합니다. stat()함수의 인자로는 const char* path, struct stat* buf를 받는데 이때 path는 파일의 경로, buf는 파일의 정보가 들어갈 구조체 포인터입니다. 따라서 구현할 때 path에는 text1, text2를 입력하고 buf에는 구조체 변수 stat1, stat2를 입력하면 될 것 같습니다.

**Comment by DrNeuroAI** [comment]
2021-05-06 KimDyun 확인

**Comment by byoung-min** [comment]
2021-05-06 Byoung-min 확인
