### ISSUE TITLE
filestat 코드 리뷰

### ISSUE THREAD

**Issue by jangsik2** [DrNeuroAI/Assignment2#30]
파일을 불러오기 위해 stat()이란 함수를 공부할 때 과제 ppt에서 제공해주신 함수 정보로 쉽게 공부를 진행할 수 있었습니다.

**Comment by byoung-min** [comment]
2021-05-06 리뷰 확인

**Comment by DrNeuroAI** [comment]
2021-05-06 리뷰 확인.
