### ISSUE TITLE
datecmp 코드 리뷰

### ISSUE THREAD

**Issue by DrNeuroAI** [DrNeuroAI/Assignment2#32]
두 텍스트의 월(month)0을 먼저 비교한 다음 월이 같을 때 일(day)을 비교하는 식으로 코드를 구현했습니다.
로직 자체를 구현하는  것에 큰 어려움은 없었고 다만 tm_mon 변수 값 범위가 0~11인 것만 주의했습니다.

**Comment by jangsik2** [comment]
2021-05-06 리뷰 확인

**Comment by byoung-min** [comment]
2021-05-06 리뷰 확인
