### ISSUE TITLE
sizecmp 기반 기술 조사

### ISSUE THREAD

**Issue by jangsik2** [DrNeuroAI/Assignment2#33]
파일의 사이즈를 알기 위해서는 stat함수의 멤버 변수 중 off_t st_size변수를 사용하여 나타내야 합니다. 이때 st_size변수는 bytes에서의 파일 크기를 나타낸 것이고 파일 두개를 비교하기 위해서는 해당 변수를 int형으로 변환하여 비교를 진행해야 할 것 같습니다.

**Comment by byoung-min** [comment]
2021-05-06 확인

**Comment by DrNeuroAI** [comment]
2021-05-06 확인
