### ISSUE TITLE
timecmp 코드 리뷰

### ISSUE THREAD

**Issue by DrNeuroAI** [DrNeuroAI/Assignment2#34]
로직은 datecmp 코드와 동일하기 때문에 쉽게 timecmp 코드를 작성할 수 있었습니다.
사전에 tm_hour와 tm_min의 값 범위를 조사한 것도 도움되었습니다.

**Comment by jangsik2** [comment]
2021-05-06 리뷰 확인

**Comment by byoung-min** [comment]
2021-05-06 리뷰 확인
