### ISSUE TITLE
sizecmp 코드 리뷰

### ISSUE THREAD

**Issue by jangsik2** [DrNeuroAI/Assignment2#36]
파일의 크기를 구하기 위해 공부를 하면서 stat()함수에 다양한 멤버 변수들이 있다는 것을 알 수 있었습니다. 또한 이때 멤버 변수 off_t st_size가 bytes에서의 크기라는 것도 알 수 있었습니다.

**Comment by DrNeuroAI** [comment]
2021-05-06 리뷰 확인

**Comment by byoung-min** [comment]
2021-05-06 리뷰 확인
