### ISSUE TITLE
filetime 코드 리뷰

### ISSUE THREAD

**Issue by byoung-min** [DrNeuroAI/Assignment2#37]
localtime() 함수를 이용하여 파일의 time_t값을 활용할 수 있도록 가공시킬수 있었습니다.
struct stat과 struct tm에 대해 공부한 것이 도움이 되었습니다.

**Comment by jangsik2** [comment]
2021-05-06 리뷰 확인

**Comment by DrNeuroAI** [comment]
2021-05-06 리뷰 확인.
