### ISSUE TITLE
filetime 기반 기술 조사

### ISSUE THREAD

**Issue by byoung-min** [DrNeuroAI/Assignment2#39]
struct tm 구조체를 사용하여 현재의 날짜와 시간에 관한 정보를 표현합니다. 이 구조체는 9개의 int형 멤버 변수를 갖고 있으며 struct tm {
  int tm_sec;
  int tm_min;
  int tm_hour;
  int tm_mday;
  int tm_mon;
  int tm_year;
  int tm_wday;
  int tm_yday;
  int tm_isdst;
};
다음의 구조를 가집니다. 
tm_sec은 현재 시각이 몇초 인지를 뜻하며 0~61의 범위로 표현합니다. 윤초를 도입하여 시간 보정하는 경우 있어 61이 존재합니다.
tm_min은 현재 시각이 몇 분인지를 뜻하며 0~59의 범위로 표현합니다.
tm_hour는 현재 시각이 몇 시인지를 뜻하며 0~23의 범위로 표현합니다.
tm_mday는 지금이 몇일 인지를 뜻하며 1~31의 범위로 표현합니다.
tm_mon은 지금이 몇 월인지 뜻하며 0~11의 범위로 표현합니다. 0인 경우 1월입니다. 
tm_year은 지금이 몇 년인지를 뜻하며 1900이후 기준으로 약 2021년이면 121이 들어가게 됩니다.
tm_wday는 지금이 무슨 요일인지를 뜻하며 0~6 으로 표현합니다. 
tm_yday는 1월 1일 기준으로 몇 일이 지났는지를 뜻하며 0~365입니다.
tm_isdst는 서머 타임제를 실시하고 있는지 아닌지를 뜻합니다.

**Comment by jangsik2** [comment]
2021-05-06 확인

**Comment by KimDyun** [comment]
2021-05-06 확인

**Comment by DrNeuroAI** [comment]
2021-05-06 확인
