### ISSUE TITLE
blockcmp 코드 리뷰

### ISSUE THREAD

**Issue by byoung-min** [DrNeuroAI/Assignment2#41]
struct stat의 st_blocks의 st_blocks 멤버 변수를 통해 block 크기 비교를 할 수 있도록 구현하였습니다.
block들의 개수를 int형으로 반환하여 저장하고 이를 if문을 통하여 비교할 수 있었습니다.

**Comment by DrNeuroAI** [comment]
2021-05-06 리뷰 확인.

**Comment by jangsik2** [comment]
2021-05-06 리뷰 확인
