### ISSUE TITLE
blockcmp 기반 기술 조사

### ISSUE THREAD

**Issue by byoung-min** [DrNeuroAI/Assignment2#42]
struct stat의 st_blocks 멤버 변수를 int형 변수로 저장하여 두개의 파일의 block 크기를 비교하는데 사용했습니다. st_blocks는 할당된 512Byte 블록들의 갯수를 뜻하게 됩니다. 멤버 변수의 인자형은 blkcnt입니다.

**Comment by jangsik2** [comment]
2021-05-06 확인

**Comment by DrNeuroAI** [comment]
2021-05-06 확인
